import { createServer } from 'http';
import express from 'express';
import cors from 'cors';
import { Server } from 'socket.io';
import { createAdapter } from '@socket.io/redis-adapter';
import env from './config/env';
import { redis, redisPub, redisSub } from '@/lib/redis';
import { authMiddleware } from './middleware/auth';
import { registerPostHandlers } from './handlers/postHandlers';
import { registerCommentHandlers } from './handlers/commentHandlers';
import { registerFeedHandlers } from './handlers/feedHandlers';
import { registerTypingHandlers } from './handlers/typingHandlers';
import { registerNotificationHandlers } from './handlers/notificationHandlers';
import { registerMessageHandlers } from './handlers/messageHandlers';
import { registerChannelHandlers } from './handlers/channelHandlers';
import { PresenceService } from './services/socket/presenceService';
import { sendMatchNotification } from './services/matching/utils/notificationUtils';
import matchingRoutes from './routes/matching';
import analyticsRoutes from './routes/analytics';
import type { MatchNotification } from './services/matching/types';
import { startMatchingScheduler, triggerMatchingJob } from './services/matching/processors/schedule';
import { prisma } from '@/lib/prisma';
import { findMatchingProjectsForMemberProfile, findMatchingTeamsForMemberProfile } from './services/matching/matchingService';
import type {
  ServerToClientEvents,
  ClientToServerEvents,
  InterServerEvents,
  SocketData
} from '@xovira/types';

const app = express();
app.use(express.json({ limit: '1mb' }));
app.use(
  cors({
    origin: env.CORS_ORIGIN.split(','),
    credentials: true,
  })
);

app.get('/health', (_req: any, res: any) => {
  res.json({
    status: 'ok',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
  });
});

app.post('/notifications/match', async (req: any, res: any) => {
  try {
    const payload = (req.body ?? {}) as Partial<MatchNotification>;
    const { userId, matchId, matchType, matchTitle, score, reason } = payload;
    const validTypes: Array<MatchNotification['matchType']> = ['project', 'proposal', 'team', 'profile'];

    if (
      !userId ||
      !matchId ||
      !matchType ||
      !validTypes.includes(matchType) ||
      !matchTitle ||
      typeof reason !== 'string'
    ) {
      return res.status(400).json({
        error: 'userId, matchId, matchType, matchTitle and reason are required',
        validMatchTypes: validTypes,
      });
    }

    await sendMatchNotification({
      userId,
      matchId,
      matchType,
      matchTitle,
      score: typeof score === 'number' ? score : Number(score ?? 0),
      reason,
    });

    return res.status(202).json({ status: 'queued' });
  } catch (error) {
    console.error('Failed to process match notification', error);
    return res.status(500).json({ error: 'Failed to process notification' });
  }
});

app.use('/v1/matching', matchingRoutes);
app.use('/v1/analytics', analyticsRoutes);


const httpServer = createServer(app);

const io: Server<ClientToServerEvents, ServerToClientEvents, InterServerEvents, SocketData> = new Server(httpServer, {
  cors: {
    origin: env.CORS_ORIGIN.split(','),
    methods: ['GET', 'POST'],
    credentials: true,
  },
  transports: ['websocket', 'polling'],
  pingTimeout: 60000,
  pingInterval: 25000,
});

// Setup Redis adapter for scaling across multiple instances
io.adapter(createAdapter(redisPub, redisSub));

// Authentication middleware
io.use(authMiddleware);

// Optional: listen to Redis pub/sub channel for notifications generated by other services
redisSub.subscribe('notifications').catch((err) => {
  console.error('Failed to subscribe to notifications channel', err);
});

redisSub.on('message', (channel, message) => {
  if (channel !== 'notifications') return;
  try {
    const payload = JSON.parse(message);
    const { userId, notification } = payload;
    if (!userId || !notification) return;
    io.to(`user:${userId}`).emit('notification:new', { notification });
  } catch (err) {
    console.error('Error handling notification message', err);
  }
});

// Connection handler
io.on('connection', async (socket) => {
  console.log(`✅ User connected: ${socket.data.userId} (${socket.id})`);

  try {
    // ✅ Pass socketId to track multiple connections
    await PresenceService.setUserOnline(socket.data.userId, socket.id);

    await socket.join(`user:${socket.data.userId}`);

    io.emit('user:online', {
      userId: socket.data.userId,
      username: socket.data.username,
      timestamp: new Date().toISOString(),
    });

    // Register event handlers
    registerPostHandlers(io, socket);
    registerCommentHandlers(io, socket);
    registerFeedHandlers(io, socket);
    registerTypingHandlers(io, socket);
    registerNotificationHandlers(io, socket);
    registerMessageHandlers(io, socket);
    registerChannelHandlers(io, socket);

    socket.on('disconnect', async (reason) => {
      console.log(`❌ User disconnected: ${socket.data.userId} (${reason})`);

      try {
        // ✅ Pass socketId to only remove this connection
        await PresenceService.setUserOffline(socket.data.userId, socket.id);

        // Check if user is actually offline (no other connections)
        const isStillOnline = await PresenceService.isUserOnline(socket.data.userId);
        
        if (!isStillOnline) {
          io.emit('user:offline', {
            userId: socket.data.userId,
            username: socket.data.username,
            timestamp: new Date().toISOString(),
          });
        }
      } catch (error) {
        console.error('Error handling disconnect:', error);
      }
    });

  } catch (error) {
    console.error('Error in connection handler:', error);
    socket.disconnect();
  }
});

// Trigger a matching run immediately on startup (no HTTP call needed)
(async () => {
  try {
    await startMatchingScheduler();
    console.log('[service-server] startup matching job enqueued');
  } catch (error) {
    console.error('[service-server] startup matching trigger failed', error);
  }
})();

// User-centric matching endpoint: compute matches using User (by userId)
app.get('/v1/matching/user/:userId', async (req: any, res: any) => {
  try {
    const { userId } = req.params;
    const limit = Number(req.query.limit ?? 20);

    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: {
        id: true,
        isActive: true,
        skills: { select: { skill: { select: { name: true } } } },
        memberProfile: { select: { rolePreferences: true, industryPreferences: true } },
        founderProfile: { select: { industryPreferences: true, locationPreferences: true } },
        investorProfile: { select: { preferredIndustries: true, preferredStages: true, geographicFocus: true } },
        proposals: { where: { category: 'COFOUNDER' }, select: { id: true }, take: 1 },
      },
    });

    if (!user || !user.isActive) {
      return res.status(404).json({ error: 'User not found or inactive' });
    }

    const [teams, projects] = await Promise.all([
      findMatchingTeamsForMemberProfile(userId, limit),
      findMatchingProjectsForMemberProfile(userId, limit),
    ]);

    const roleRefs = [
      ...(user.memberProfile?.rolePreferences || []),
      ...(user.skills || []).map((us: { skill: { name: string | null } | null }) => us.skill?.name).filter(Boolean) as string[],
      ...(user.investorProfile ? ['Investor'] : []),
      ...(user.founderProfile ? ['Founder'] : []),
      ...((user.proposals && user.proposals.length > 0) ? ['CoFounder'] : []),
    ];
    const industryRefs = [
      ...(user.memberProfile?.industryPreferences || []),
      ...(user.founderProfile?.industryPreferences || []),
      ...(user.investorProfile?.preferredIndustries || []),
    ];
    const stageRefs = [
      ...(user.investorProfile?.preferredStages || []),
    ];
    const geoRefs = [
      ...(user.founderProfile?.locationPreferences || []),
      ...(user.investorProfile?.geographicFocus || []),
    ];
    return res.json({
      userId,
      refs: { roleRefs, industryRefs, stageRefs, geoRefs },
      teams,
      projects,
      count: { teams: teams.length, projects: projects.length },
    });
  } catch (error) {
    console.error('[service-server] user matching failed', error);
    return res.status(500).json({ error: 'Failed to compute user matches' });
  }
});


// Graceful shutdown
process.on('SIGTERM', async () => {
  console.log('SIGTERM received, closing server...');
  
  io.close(() => {
    console.log('Socket.IO server closed');
  });

  await redis.quit();
  await redisPub.quit();
  await redisSub.quit();
  
  process.exit(0);
});

process.on('SIGINT', async () => {
  console.log('SIGINT received, closing server...');
  
  io.close(() => {
    console.log('Socket.IO server closed');
  });

  await redis.quit();
  await redisPub.quit();
  await redisSub.quit();
  
  process.exit(0);
});

// Start server
const PORT = parseInt(env.PORT, 10);

httpServer.listen(PORT, () => {
  console.log(`🚀 Socket.IO server running on port ${PORT}`);
  console.log(`📡 Environment: ${env.NODE_ENV}`);
  console.log(`🔗 CORS Origin: ${env.CORS_ORIGIN}`);
});