import {
    Type,
    List,
    Calendar,
    Hash,
    Tag,
    CheckSquare,
    DollarSign,
    Globe,
    Mail,
    Phone,
    AlignLeft,
    FunctionSquare,
    FileText,
    Link2,
    User,
    BarChart3,
    Gauge,
    Languages,
    Smile,
    ListTodo,
    MapPin,
    Star,
    Vote,
    PenLine,
    Square,
    ListChecks,
} from 'lucide-react';

export interface FieldTypeOption {
    id: string;
    label: string;
    type: string;
    icon: React.ComponentType<{ className?: string }>;
    color: string;
    isAi?: boolean;
}

/** DB type to use when creating - maps display types to Prisma CustomFieldType */
export const TYPE_TO_DB: Record<string, string> = {
    TEXT: 'TEXT',
    TEXT_AREA: 'TEXT',
    LONG_TEXT: 'TEXT',
    NUMBER: 'NUMBER',
    DROPDOWN: 'DROPDOWN',
    DATE: 'DATE',
    CHECKBOX: 'CHECKBOX',
    URL: 'URL',
    WEBSITE: 'URL',
    EMAIL: 'EMAIL',
    PHONE: 'PHONE',
    SUMMARY: 'TEXT',
    CUSTOM_TEXT: 'TEXT',
    CUSTOM_DROPDOWN: 'DROPDOWN',
    PROGRESS_UPDATES: 'TEXT',
    TRANSLATION: 'TEXT',
    LABELS: 'DROPDOWN',
    MONEY: 'CURRENCY',
    CURRENCY: 'CURRENCY',
    FORMULA: 'FORMULA',
    FILES: 'TEXT',
    RELATIONSHIP: 'TEXT',
    PEOPLE: 'USER',
    USER: 'USER',
    PROGRESS_AUTO: 'NUMBER',
    PROGRESS_MANUAL: 'NUMBER',
    CATEGORIZE: 'DROPDOWN',
    SENTIMENT: 'DROPDOWN',
    TASKS: 'TEXT',
    LOCATION: 'LOCATION',
    RATING: 'RATING',
    VOTING: 'NUMBER',
    SIGNATURE: 'TEXT',
    BUTTON: 'TEXT',
    ACTION_ITEMS: 'TEXT',
    TSHIRT_SIZE: 'DROPDOWN',
    MULTI_SELECT: 'MULTI_SELECT',
};

export const AI_FIELDS: FieldTypeOption[] = [
    { id: 'summary', label: 'Summary', type: 'SUMMARY', icon: Type, color: 'text-purple-600', isAi: true },
    { id: 'custom_text', label: 'Custom Text', type: 'CUSTOM_TEXT', icon: Type, color: 'text-purple-600', isAi: true },
    { id: 'custom_dropdown', label: 'Custom Dropdown', type: 'CUSTOM_DROPDOWN', icon: List, color: 'text-purple-600', isAi: true },
];

export const ALL_FIELDS: FieldTypeOption[] = [
    { id: 'dropdown', label: 'Dropdown', type: 'DROPDOWN', icon: List, color: 'text-emerald-600' },
    { id: 'text', label: 'Text', type: 'TEXT', icon: Type, color: 'text-blue-600' },
    { id: 'date', label: 'Date', type: 'DATE', icon: Calendar, color: 'text-amber-600' },
    { id: 'textarea', label: 'Text area (Long Text)', type: 'TEXT_AREA', icon: AlignLeft, color: 'text-blue-600' },
    { id: 'number', label: 'Number', type: 'NUMBER', icon: Hash, color: 'text-zinc-800' },
    { id: 'labels', label: 'Labels', type: 'LABELS', icon: Tag, color: 'text-emerald-600' },
    { id: 'checkbox', label: 'Checkbox', type: 'CHECKBOX', icon: CheckSquare, color: 'text-red-600' },
    { id: 'money', label: 'Money', type: 'MONEY', icon: DollarSign, color: 'text-emerald-600' },
    { id: 'website', label: 'Website', type: 'URL', icon: Globe, color: 'text-red-600' },
    { id: 'formula', label: 'Formula', type: 'FORMULA', icon: FunctionSquare, color: 'text-emerald-600' },
    { id: 'custom_text_all', label: 'Custom Text', type: 'CUSTOM_TEXT', icon: Type, color: 'text-purple-600' },
    { id: 'summary_all', label: 'Summary', type: 'SUMMARY', icon: Type, color: 'text-purple-600' },
    { id: 'progress_updates', label: 'Progress Updates', type: 'PROGRESS_UPDATES', icon: FileText, color: 'text-purple-600' },
    { id: 'files', label: 'Files', type: 'FILES', icon: FileText, color: 'text-purple-600' },
    { id: 'relationship', label: 'Relationship', type: 'RELATIONSHIP', icon: Link2, color: 'text-blue-600' },
    { id: 'people', label: 'People', type: 'PEOPLE', icon: User, color: 'text-red-600' },
    { id: 'progress_auto', label: 'Progress (Auto)', type: 'PROGRESS_AUTO', icon: BarChart3, color: 'text-orange-600' },
    { id: 'email_all', label: 'Email', type: 'EMAIL', icon: Mail, color: 'text-red-600' },
    { id: 'phone_all', label: 'Phone', type: 'PHONE', icon: Phone, color: 'text-red-600' },
    { id: 'categorize', label: 'Categorize', type: 'CATEGORIZE', icon: List, color: 'text-purple-600' },
    { id: 'custom_dropdown_all', label: 'Custom Dropdown', type: 'CUSTOM_DROPDOWN', icon: List, color: 'text-purple-600' },
    { id: 'translation', label: 'Translation', type: 'TRANSLATION', icon: Languages, color: 'text-purple-600' },
    { id: 'sentiment', label: 'Sentiment', type: 'SENTIMENT', icon: Smile, color: 'text-purple-600' },
    { id: 'tasks', label: 'Tasks', type: 'TASKS', icon: ListTodo, color: 'text-blue-600' },
    { id: 'location', label: 'Location', type: 'LOCATION', icon: MapPin, color: 'text-red-600' },
    { id: 'progress_manual', label: 'Progress (Manual)', type: 'PROGRESS_MANUAL', icon: Gauge, color: 'text-amber-600' },
    { id: 'rating', label: 'Rating', type: 'RATING', icon: Star, color: 'text-amber-600' },
    { id: 'voting', label: 'Voting', type: 'VOTING', icon: Vote, color: 'text-purple-600' },
    { id: 'signature', label: 'Signature', type: 'SIGNATURE', icon: PenLine, color: 'text-green-600' },
    { id: 'button', label: 'Button', type: 'BUTTON', icon: Square, color: 'text-purple-600' },
    { id: 'action_items', label: 'Action Items', type: 'ACTION_ITEMS', icon: ListChecks, color: 'text-purple-600' },
    { id: 'tshirt_size', label: 'T-shirt Size', type: 'TSHIRT_SIZE', icon: List, color: 'text-purple-600' },
];

/** Unique field types for the Type dropdown (form modal) - matches CustomFieldRenderer */
export const FIELD_TYPE_DROPDOWN_OPTIONS: FieldTypeOption[] = [
    { id: 'text', label: 'Text', type: 'TEXT', icon: Type, color: 'text-blue-600' },
    { id: 'textarea', label: 'Text area (Long Text)', type: 'TEXT_AREA', icon: AlignLeft, color: 'text-blue-600' },
    { id: 'number', label: 'Number', type: 'NUMBER', icon: Hash, color: 'text-zinc-800' },
    { id: 'dropdown', label: 'Dropdown', type: 'DROPDOWN', icon: List, color: 'text-emerald-600' },
    { id: 'date', label: 'Date', type: 'DATE', icon: Calendar, color: 'text-amber-600' },
    { id: 'checkbox', label: 'Checkbox', type: 'CHECKBOX', icon: CheckSquare, color: 'text-red-600' },
    { id: 'url', label: 'Website', type: 'URL', icon: Globe, color: 'text-red-600' },
    { id: 'email', label: 'Email', type: 'EMAIL', icon: Mail, color: 'text-red-600' },
    { id: 'phone', label: 'Phone', type: 'PHONE', icon: Phone, color: 'text-red-600' },
    { id: 'summary', label: 'Summary', type: 'SUMMARY', icon: Type, color: 'text-purple-600' },
    { id: 'custom_text', label: 'Custom Text', type: 'CUSTOM_TEXT', icon: Type, color: 'text-purple-600' },
    { id: 'custom_dropdown', label: 'Custom Dropdown', type: 'CUSTOM_DROPDOWN', icon: List, color: 'text-purple-600' },
    { id: 'labels', label: 'Labels', type: 'LABELS', icon: Tag, color: 'text-emerald-600' },
    { id: 'money', label: 'Money', type: 'MONEY', icon: DollarSign, color: 'text-emerald-600' },
    { id: 'formula', label: 'Formula', type: 'FORMULA', icon: FunctionSquare, color: 'text-emerald-600' },
    { id: 'files', label: 'Files', type: 'FILES', icon: FileText, color: 'text-purple-600' },
    { id: 'relationship', label: 'Relationship', type: 'RELATIONSHIP', icon: Link2, color: 'text-blue-600' },
    { id: 'people', label: 'People', type: 'PEOPLE', icon: User, color: 'text-red-600' },
    { id: 'progress_auto', label: 'Progress (Auto)', type: 'PROGRESS_AUTO', icon: BarChart3, color: 'text-orange-600' },
    { id: 'progress_manual', label: 'Progress (Manual)', type: 'PROGRESS_MANUAL', icon: Gauge, color: 'text-amber-600' },
    { id: 'categorize', label: 'Categorize', type: 'CATEGORIZE', icon: List, color: 'text-purple-600' },
    { id: 'translation', label: 'Translation', type: 'TRANSLATION', icon: Languages, color: 'text-purple-600' },
    { id: 'sentiment', label: 'Sentiment', type: 'SENTIMENT', icon: Smile, color: 'text-purple-600' },
    { id: 'tasks', label: 'Tasks', type: 'TASKS', icon: ListTodo, color: 'text-blue-600' },
    { id: 'location', label: 'Location', type: 'LOCATION', icon: MapPin, color: 'text-red-600' },
    { id: 'rating', label: 'Rating', type: 'RATING', icon: Star, color: 'text-amber-600' },
    { id: 'voting', label: 'Voting', type: 'VOTING', icon: Vote, color: 'text-purple-600' },
    { id: 'signature', label: 'Signature', type: 'SIGNATURE', icon: PenLine, color: 'text-green-600' },
    { id: 'button', label: 'Button', type: 'BUTTON', icon: Square, color: 'text-purple-600' },
    { id: 'action_items', label: 'Action Items', type: 'ACTION_ITEMS', icon: ListChecks, color: 'text-purple-600' },
    { id: 'tshirt_size', label: 'T-shirt Size', type: 'TSHIRT_SIZE', icon: List, color: 'text-purple-600' },
    { id: 'progress_updates', label: 'Progress Updates', type: 'PROGRESS_UPDATES', icon: FileText, color: 'text-purple-600' },
];
