const INDUSTRY_OPTIONS = [
  { value: "technology", label: "Technology" },
  { value: "healthcare", label: "Healthcare" },
  { value: "finance", label: "Finance" },
  { value: "education", label: "Education" },
  { value: "retail", label: "Retail" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "real_estate", label: "Real Estate" },
  { value: "transportation", label: "Transportation" },
  { value: "energy", label: "Energy" },
  { value: "agriculture", label: "Agriculture" },
  { value: "entertainment", label: "Entertainment" },
  { value: "hospitality", label: "Hospitality" },
  { value: "consulting", label: "Consulting" },
  { value: "marketing", label: "Marketing" },
  { value: "legal", label: "Legal" },
  { value: "non_profit", label: "Non-profit" },
  { value: "government", label: "Government" },
  { value: "construction", label: "Construction" },
  { value: "automotive", label: "Automotive" },
  { value: "aerospace", label: "Aerospace" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "media", label: "Media" },
  { value: "food_beverage", label: "Food & Beverage" },
  { value: "fashion", label: "Fashion" },
  { value: "sports", label: "Sports" },
  { value: "gaming", label: "Gaming" },
  { value: "blockchain", label: "Blockchain/Crypto" },
  { value: "ai_ml", label: "AI/Machine Learning" },
  { value: "biotech", label: "Biotechnology" },
  { value: "environmental", label: "Environmental" },
  { value: "other", label: "Other" }
];

const CURRENCY_OPTIONS = [
  { value: "USD", label: "USD" },
  { value: "EUR", label: "EUR" },
  { value: "GBP", label: "GBP" },
  { value: "JPY", label: "JPY" },
  { value: "CNY", label: "CNY" },
  { value: "INR", label: "INR" },
  { value: "CAD", label: "CAD" },
  { value: "AUD", label: "AUD" },
  { value: "CHF", label: "CHF" },
  { value: "SEK", label: "SEK" },
  { value: "NOK", label: "NOK" },
  { value: "DKK", label: "DKK" },
  { value: "NZD", label: "NZD" },
  { value: "SGD", label: "SGD" },
  { value: "HKD", label: "HKD" },
  { value: "KRW", label: "KRW" },
  { value: "BRL", label: "BRL" },
  { value: "MXN", label: "MXN" },
  { value: "ARS", label: "ARS" },
  { value: "COP", label: "COP" },
  { value: "CLP", label: "CLP" },
  { value: "PEN", label: "PEN" },
  { value: "ZAR", label: "ZAR" },
  { value: "NGN", label: "NGN" },
  { value: "EGP", label: "EGP" },
  { value: "AED", label: "AED" },
  { value: "SAR", label: "SAR" },
  { value: "TRY", label: "TRY" },
  { value: "RUB", label: "RUB" },
  { value: "PLN", label: "PLN" },
  { value: "CZK", label: "CZK" },
  { value: "HUF", label: "HUF" },
  { value: "RON", label: "RON" },
  { value: "BGN", label: "BGN" },
  { value: "HRK", label: "HRK" },
  { value: "THB", label: "THB" },
  { value: "MYR", label: "MYR" },
  { value: "IDR", label: "IDR" },
  { value: "PHP", label: "PHP" },
  { value: "VND", label: "VND" }
];

const LANGUAGE_OPTIONS = [
  { value: "en", label: "English" },
  { value: "es", label: "Español" },
  { value: "fr", label: "Français" },
  { value: "de", label: "Deutsch" },
  { value: "it", label: "Italiano" },
  { value: "pt", label: "Português" },
  { value: "ru", label: "Русский" },
  { value: "zh", label: "中文" },
  { value: "ja", label: "日本語" },
  { value: "ko", label: "한국어" },
  { value: "ar", label: "العربية" },
  { value: "hi", label: "हिन्दी" },
  { value: "tr", label: "Türkçe" },
  { value: "nl", label: "Nederlands" },
  { value: "sv", label: "Svenska" },
  { value: "pl", label: "Polski" },
  { value: "da", label: "Dansk" },
  { value: "no", label: "Norsk" },
  { value: "fi", label: "Suomi" },
  { value: "th", label: "ไทย" },
  { value: "vi", label: "Tiếng Việt" },
  { value: "id", label: "Bahasa Indonesia" },
  { value: "ms", label: "Bahasa Malaysia" }
];

const MENTORSHIP_AREAS = [
  { value: "business_strategy", label: "Business Strategy" },
  { value: "marketing_sales", label: "Marketing & Sales" },
  { value: "product_development", label: "Product Development" },
  { value: "fundraising", label: "Fundraising" },
  { value: "leadership", label: "Leadership" },
  { value: "operations", label: "Operations" },
  { value: "technology", label: "Technology" },
  { value: "finance", label: "Finance" },
  { value: "legal", label: "Legal" },
  { value: "hr", label: "HR" },
  { value: "international_expansion", label: "International Expansion" },
  { value: "digital_marketing", label: "Digital Marketing" },
  { value: "b2b_sales", label: "B2B Sales" },
  { value: "customer_success", label: "Customer Success" },
  { value: "supply_chain", label: "Supply Chain" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "retail", label: "Retail" },
  { value: "ecommerce", label: "E-commerce" },
  { value: "saas", label: "SaaS" },
  { value: "mobile_apps", label: "Mobile Apps" },
  { value: "ai_ml", label: "AI/ML" },
  { value: "blockchain", label: "Blockchain" },
  { value: "iot", label: "IoT" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "data_analytics", label: "Data Analytics" },
  { value: "cloud_computing", label: "Cloud Computing" },
  { value: "healthcare", label: "Healthcare" },
  { value: "fintech", label: "Fintech" },
  { value: "edtech", label: "Edtech" },
  { value: "proptech", label: "Proptech" },
  { value: "cleantech", label: "Cleantech" },
  { value: "social_impact", label: "Social Impact" }
];

const EXPERTISE_AREAS = [
  { value: "c_suite_leadership", label: "C-Suite Leadership" },
  { value: "vp_level_management", label: "VP-Level Management" },
  { value: "startup_founding", label: "Startup Founding" },
  { value: "scaleup_growth", label: "Scale-up Growth" },
  { value: "exit_strategy", label: "Exit Strategy" },
  { value: "ipo_process", label: "IPO Process" },
  { value: "mna", label: "M&A" },
  { value: "venture_capital", label: "Venture Capital" },
  { value: "angel_investing", label: "Angel Investing" },
  { value: "board_advisory", label: "Board Advisory" },
  { value: "technical_architecture", label: "Technical Architecture" },
  { value: "team_building", label: "Team Building" },
  { value: "culture_development", label: "Culture Development" },
  { value: "international_markets", label: "International Markets" },
  { value: "regulatory_compliance", label: "Regulatory Compliance" },
  { value: "patent_strategy", label: "Patent Strategy" },
  { value: "brand_building", label: "Brand Building" },
  { value: "partnership_development", label: "Partnership Development" },
  { value: "channel_sales", label: "Channel Sales" },
  { value: "direct_sales", label: "Direct Sales" },
  { value: "inside_sales", label: "Inside Sales" },
  { value: "field_marketing", label: "Field Marketing" },
  { value: "content_marketing", label: "Content Marketing" },
  { value: "seo_sem", label: "SEO/SEM" },
  { value: "social_media", label: "Social Media" },
  { value: "pr", label: "PR" },
  { value: "customer_acquisition", label: "Customer Acquisition" },
  { value: "customer_retention", label: "Customer Retention" },
  { value: "product_market_fit", label: "Product-Market Fit" },
  { value: "mvp_development", label: "MVP Development" },
  { value: "agile_scrum", label: "Agile/Scrum" },
  { value: "devops", label: "DevOps" },
  { value: "quality_assurance", label: "Quality Assurance" },
  { value: "user_experience", label: "User Experience" },
  { value: "design_thinking", label: "Design Thinking" }
];

const PRODUCT_CATEGORIES = [
  { value: "software_saas", label: "Software/SaaS" },
  { value: "mobile_apps", label: "Mobile Apps" },
  { value: "web_apps", label: "Web Applications" },
  { value: "enterprise_software", label: "Enterprise Software" },
  { value: "consumer_electronics", label: "Consumer Electronics" },
  { value: "hardware_iot", label: "Hardware/IoT" },
  { value: "medical_devices", label: "Medical Devices" },
  { value: "industrial_equipment", label: "Industrial Equipment" },
  { value: "consumer_products", label: "Consumer Products" },
  { value: "b2b_services", label: "B2B Services" },
  { value: "consulting", label: "Consulting" },
  { value: "training_education", label: "Training/Education" },
  { value: "content_media", label: "Content/Media" },
  { value: "gaming", label: "Gaming" },
  { value: "financial_services", label: "Financial Services" },
  { value: "insurance", label: "Insurance" },
  { value: "real_estate", label: "Real Estate" },
  { value: "travel_hospitality", label: "Travel/Hospitality" },
  { value: "food_beverage", label: "Food & Beverage" },
  { value: "fashion_apparel", label: "Fashion/Apparel" },
  { value: "beauty_cosmetics", label: "Beauty/Cosmetics" },
  { value: "sports_fitness", label: "Sports/Fitness" },
  { value: "automotive", label: "Automotive" },
  { value: "energy_utilities", label: "Energy/Utilities" },
  { value: "agriculture", label: "Agriculture" },
  { value: "construction", label: "Construction" },
  { value: "legal_services", label: "Legal Services" },
  { value: "marketing_services", label: "Marketing Services" },
  { value: "design_services", label: "Design Services" },
  { value: "other", label: "Other" }
];

const TIMEZONE_OPTIONS = [
  { value: "UTC-12:00", label: "UTC-12:00" },
  { value: "UTC-11:00", label: "UTC-11:00" },
  { value: "UTC-10:00", label: "UTC-10:00" },
  { value: "UTC-09:00", label: "UTC-09:00" },
  { value: "UTC-08:00", label: "UTC-08:00" },
  { value: "UTC-07:00", label: "UTC-07:00" },
  { value: "UTC-06:00", label: "UTC-06:00" },
  { value: "UTC-05:00", label: "UTC-05:00" },
  { value: "UTC-04:00", label: "UTC-04:00" },
  { value: "UTC-03:00", label: "UTC-03:00" },
  { value: "UTC-02:00", label: "UTC-02:00" },
  { value: "UTC-01:00", label: "UTC-01:00" },
  { value: "UTC+00:00", label: "UTC+00:00" },
  { value: "UTC+01:00", label: "UTC+01:00" },
  { value: "UTC+02:00", label: "UTC+02:00" },
  { value: "UTC+03:00", label: "UTC+03:00" },
  { value: "UTC+04:00", label: "UTC+04:00" },
  { value: "UTC+05:00", label: "UTC+05:00" },
  { value: "UTC+06:00", label: "UTC+06:00" },
  { value: "UTC+07:00", label: "UTC+07:00" },
  { value: "UTC+08:00", label: "UTC+08:00" },
  { value: "UTC+09:00", label: "UTC+09:00" },
  { value: "UTC+10:00", label: "UTC+10:00" },
  { value: "UTC+11:00", label: "UTC+11:00" },
  { value: "UTC+12:00", label: "UTC+12:00" }
];

const COUNTRY_OPTIONS = [
  { value: "united_states", label: "United States" },
  { value: "canada", label: "Canada" },
  { value: "united_kingdom", label: "United Kingdom" },
  { value: "germany", label: "Germany" },
  { value: "france", label: "France" },
  { value: "spain", label: "Spain" },
  { value: "italy", label: "Italy" },
  { value: "netherlands", label: "Netherlands" },
  { value: "sweden", label: "Sweden" },
  { value: "norway", label: "Norway" },
  { value: "denmark", label: "Denmark" },
  { value: "finland", label: "Finland" },
  { value: "switzerland", label: "Switzerland" },
  { value: "austria", label: "Austria" },
  { value: "belgium", label: "Belgium" },
  { value: "ireland", label: "Ireland" },
  { value: "portugal", label: "Portugal" },
  { value: "poland", label: "Poland" },
  { value: "czech_republic", label: "Czech Republic" },
  { value: "hungary", label: "Hungary" },
  { value: "romania", label: "Romania" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "croatia", label: "Croatia" },
  { value: "slovenia", label: "Slovenia" },
  { value: "slovakia", label: "Slovakia" },
  { value: "estonia", label: "Estonia" },
  { value: "latvia", label: "Latvia" },
  { value: "lithuania", label: "Lithuania" },
  { value: "japan", label: "Japan" },
  { value: "south_korea", label: "South Korea" },
  { value: "china", label: "China" },
  { value: "india", label: "India" },
  { value: "singapore", label: "Singapore" },
  { value: "hong_kong", label: "Hong Kong" },
  { value: "taiwan", label: "Taiwan" },
  { value: "thailand", label: "Thailand" },
  { value: "malaysia", label: "Malaysia" },
  { value: "indonesia", label: "Indonesia" },
  { value: "philippines", label: "Philippines" },
  { value: "vietnam", label: "Vietnam" },
  { value: "australia", label: "Australia" },
  { value: "new_zealand", label: "New Zealand" },
  { value: "brazil", label: "Brazil" },
  { value: "mexico", label: "Mexico" },
  { value: "argentina", label: "Argentina" },
  { value: "chile", label: "Chile" },
  { value: "colombia", label: "Colombia" },
  { value: "peru", label: "Peru" },
  { value: "uruguay", label: "Uruguay" },
  { value: "costa_rica", label: "Costa Rica" },
  { value: "south_africa", label: "South Africa" },
  { value: "nigeria", label: "Nigeria" },
  { value: "kenya", label: "Kenya" },
  { value: "egypt", label: "Egypt" },
  { value: "morocco", label: "Morocco" },
  { value: "israel", label: "Israel" },
  { value: "uae", label: "UAE" },
  { value: "saudi_arabia", label: "Saudi Arabia" },
  { value: "turkey", label: "Turkey" },
  { value: "russia", label: "Russia" },
  { value: "ukraine", label: "Ukraine" },
  { value: "belarus", label: "Belarus" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "uzbekistan", label: "Uzbekistan" },
  { value: "georgia", label: "Georgia" },
  { value: "armenia", label: "Armenia" },
  { value: "azerbaijan", label: "Azerbaijan" },
  { value: "moldova", label: "Moldova" },
  { value: "albania", label: "Albania" },
  { value: "montenegro", label: "Montenegro" },
  { value: "serbia", label: "Serbia" },
  { value: "bosnia", label: "Bosnia" },
  { value: "macedonia", label: "Macedonia" },
  { value: "kosovo", label: "Kosovo" },
  { value: "iceland", label: "Iceland" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "malta", label: "Malta" },
  { value: "cyprus", label: "Cyprus" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "monaco", label: "Monaco" },
  { value: "san_marino", label: "San Marino" },
  { value: "vatican", label: "Vatican" },
  { value: "andorra", label: "Andorra" }
];

export {
  INDUSTRY_OPTIONS,
  CURRENCY_OPTIONS,
  LANGUAGE_OPTIONS,
  MENTORSHIP_AREAS,
  EXPERTISE_AREAS,
  PRODUCT_CATEGORIES,
  TIMEZONE_OPTIONS,
  COUNTRY_OPTIONS
};