/**
 * Shared constants for ListView: filter options, field operators, standard column config.
 */
import {
    Circle,
    Tag,
    Calendar,
    Flag,
    Users,
    Archive,
    MessageSquare,
    UserPlus,
    CalendarCheck,
    CalendarClock,
    CheckCircle2,
    Link2,
    Timer,
    MapPin,
    CalendarRange,
    Hourglass,
    Clock,
    UserCheck,
    RefreshCw,
    Box,
    Type,
    AlignLeft,
} from "lucide-react";
import type { ColumnKey } from "./listViewTypes";

export const FIELD_OPERATORS: Record<string, { id: string; label: string }[]> = {
    status: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "any_of", label: "Is any of" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    tags: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "any_of", label: "Is any of" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    dueDate: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "before", label: "Is before" },
        { id: "after", label: "Is after" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    priority: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "any_of", label: "Is any of" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    assignee: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "any_of", label: "Is any of" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    archived: [
        { id: "is_archived", label: "Is archived" },
        { id: "is_not_archived", label: "Is not archived" },
    ],
    assignedComment: [
        { id: "has", label: "Has assigned comments" },
        { id: "doesnt_have", label: "Doesn't have assigned comments" },
    ],
    createdBy: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "any_of", label: "Is any of" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    dateClosed: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "before", label: "Is before" },
        { id: "after", label: "Is after" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    dateCreated: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "before", label: "Is before" },
        { id: "after", label: "Is after" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    dateDone: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "before", label: "Is before" },
        { id: "after", label: "Is after" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    dependency: [
        { id: "has", label: "Has" },
        { id: "doesnt_have", label: "Doesn't have" },
    ],
    duration: [
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
        { id: "less_than", label: "Less than" },
        { id: "greater_than", label: "Greater than" },
        { id: "equal", label: "Equal" },
    ],
    location: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
    ],
    startDate: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "before", label: "Is before" },
        { id: "after", label: "Is after" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    timeEstimate: [
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
        { id: "less_than", label: "Less than" },
        { id: "greater_than", label: "Greater than" },
        { id: "equal", label: "Equal" },
    ],
    timeTracked: [
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
        { id: "less_than", label: "Less than" },
        { id: "greater_than", label: "Greater than" },
        { id: "equal", label: "Equal" },
    ],
    follower: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "any_of", label: "Is any of" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    taskType: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "any_of", label: "Is any of" },
    ],
    latestStatusChange: [
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "before", label: "Is before" },
        { id: "after", label: "Is after" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    name: [
        { id: "contains", label: "Contains" },
        { id: "not_contains", label: "Does not contain" },
        { id: "is", label: "Is" },
        { id: "is_not", label: "Is not" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
    description: [
        { id: "contains", label: "Contains" },
        { id: "not_contains", label: "Does not contain" },
        { id: "is_set", label: "Is set" },
        { id: "is_not_set", label: "Is not set" },
    ],
};

export const FILTER_OPTIONS = [
    { id: "status", label: "Status", icon: Circle },
    { id: "tags", label: "Tags", icon: Tag },
    { id: "dueDate", label: "Due date", icon: Calendar },
    { id: "priority", label: "Priority", icon: Flag },
    { id: "assignee", label: "Assignee", icon: Users },
    { id: "archived", label: "Archived", icon: Archive },
    { id: "assignedComment", label: "Assigned comment", icon: MessageSquare },
    { id: "createdBy", label: "Created by", icon: UserPlus },
    { id: "dateClosed", label: "Date closed", icon: CalendarCheck },
    { id: "dateCreated", label: "Date created", icon: CalendarClock },
    { id: "dateDone", label: "Date done", icon: CheckCircle2 },
    { id: "dependency", label: "Dependency", icon: Link2 },
    { id: "duration", label: "Duration", icon: Timer },
    { id: "location", label: "Location", icon: MapPin },
    { id: "startDate", label: "Start date", icon: CalendarRange },
    { id: "timeEstimate", label: "Time estimate", icon: Hourglass },
    { id: "timeTracked", label: "Time tracked", icon: Clock },
    { id: "follower", label: "Follower", icon: UserCheck },
    { id: "taskType", label: "Task type", icon: Box },
    { id: "latestStatusChange", label: "Latest status change", icon: RefreshCw },
    { id: "name", label: "Task name", icon: Type },
    { id: "description", label: "Task description", icon: AlignLeft },
];

export const STANDARD_FIELD_CONFIG: { id: ColumnKey; label: string; icon: string; isCustom?: boolean }[] = [
    { id: "name", label: "Task Name", icon: "Aa" },
    { id: "assignee", label: "Assignee", icon: "person" },
    { id: "dueDate", label: "Due date", icon: "calendar" },
    { id: "priority", label: "Priority", icon: "flag" },
    { id: "status", label: "Status", icon: "circle" },
    { id: "comments", label: "Comments", icon: "message" },
    { id: "tags", label: "Tags", icon: "tag" },
    { id: "timeTracked", label: "Time tracked", icon: "clock" },
    { id: "dateCreated", label: "Date created", icon: "calendar" },
    { id: "timeEstimate", label: "Time estimate", icon: "clock" },
    { id: "pullRequests", label: "Pull Requests", icon: "link" },
    { id: "linkedTasks", label: "Linked tasks", icon: "link" },
    { id: "taskType", label: "Type", icon: "box" },
];
